spring:
  application:
    name: Language Learning Backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/language_learning?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
    username: ${DB_USER:root}
    password: ${DB_PASS:}

    hikari:
      pool-name: LanguageLearningPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}
#      timeout: 5000ms

  cache:
    type: simple

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080
frontend:
    url: ${FRONTEND_URL}
backend:
    url: ${BACKEND_URL}
Android:
    url: ${ANDROID_URL}

jwt:
 secret: ${JWT_SECRET}
 access-token-expiration: 900000
 refresh-token-expiration: 2592000000

google:
  client-id: ${GOOGLE_CLIENT_ID}

paypal:
    client-id: ${PAYPAL_CLIENT_ID}
    client-secret: ${PAYPAL_CLIENT_SECRET}

vnpay:
  payment-url: ${VNPAY_PAYMENT_URL}
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  return-url: ${VNPAY_RETURN_URL}
  ipn-url: ${VNPAY_IPN_URL}
  version: ${VNPAY_VERSION}


ai:
  provider: groq

groq:
  api-key: ${GROQ_API_KEY}
  model: llama-3.3-70b-versatile
  base-url: https://api.groq.com/openai/v1/chat/completions